wget http://www.fosss.org/article/dabeizhou/01.jpg
wget http://www.fosss.org/article/dabeizhou/02.jpg
wget http://www.fosss.org/article/dabeizhou/03.jpg
wget http://www.fosss.org/article/dabeizhou/04.jpg
wget http://www.fosss.org/article/dabeizhou/05.jpg
wget http://www.fosss.org/article/dabeizhou/06.jpg
wget http://www.fosss.org/article/dabeizhou/07.jpg
wget http://www.fosss.org/article/dabeizhou/08.jpg
wget http://www.fosss.org/article/dabeizhou/09.jpg
wget http://www.fosss.org/article/dabeizhou/10.jpg
wget http://www.fosss.org/article/dabeizhou/11.jpg
wget http://www.fosss.org/article/dabeizhou/12.jpg
wget http://www.fosss.org/article/dabeizhou/13.jpg
wget http://www.fosss.org/article/dabeizhou/14.jpg
wget http://www.fosss.org/article/dabeizhou/15.jpg
wget http://www.fosss.org/article/dabeizhou/16.jpg
wget http://www.fosss.org/article/dabeizhou/17.jpg
wget http://www.fosss.org/article/dabeizhou/18.jpg
wget http://www.fosss.org/article/dabeizhou/19.jpg
wget http://www.fosss.org/article/dabeizhou/20.jpg
wget http://www.fosss.org/article/dabeizhou/21.jpg
wget http://www.fosss.org/article/dabeizhou/22.jpg
wget http://www.fosss.org/article/dabeizhou/23.jpg
wget http://www.fosss.org/article/dabeizhou/24.jpg
wget http://www.fosss.org/article/dabeizhou/25.jpg
wget http://www.fosss.org/article/dabeizhou/26.jpg
wget http://www.fosss.org/article/dabeizhou/27.jpg
wget http://www.fosss.org/article/dabeizhou/28.jpg
wget http://www.fosss.org/article/dabeizhou/29.jpg
wget http://www.fosss.org/article/dabeizhou/30.jpg
wget http://www.fosss.org/article/dabeizhou/31.jpg
wget http://www.fosss.org/article/dabeizhou/32.jpg
wget http://www.fosss.org/article/dabeizhou/33.jpg
wget http://www.fosss.org/article/dabeizhou/34.jpg
wget http://www.fosss.org/article/dabeizhou/35.jpg
wget http://www.fosss.org/article/dabeizhou/36.jpg
wget http://www.fosss.org/article/dabeizhou/37.jpg
wget http://www.fosss.org/article/dabeizhou/38.jpg
wget http://www.fosss.org/article/dabeizhou/39.jpg
wget http://www.fosss.org/article/dabeizhou/40.jpg
wget http://www.fosss.org/article/dabeizhou/41.jpg
wget http://www.fosss.org/article/dabeizhou/42.jpg
wget http://www.fosss.org/article/dabeizhou/43.jpg
wget http://www.fosss.org/article/dabeizhou/44.jpg
wget http://www.fosss.org/article/dabeizhou/45.jpg
wget http://www.fosss.org/article/dabeizhou/46.jpg
wget http://www.fosss.org/article/dabeizhou/47.jpg
wget http://www.fosss.org/article/dabeizhou/48.jpg
wget http://www.fosss.org/article/dabeizhou/49.jpg
wget http://www.fosss.org/article/dabeizhou/50.jpg
wget http://www.fosss.org/article/dabeizhou/51.jpg
wget http://www.fosss.org/article/dabeizhou/52.jpg
wget http://www.fosss.org/article/dabeizhou/53.jpg
wget http://www.fosss.org/article/dabeizhou/54.jpg
wget http://www.fosss.org/article/dabeizhou/55.jpg
wget http://www.fosss.org/article/dabeizhou/56.jpg
wget http://www.fosss.org/article/dabeizhou/57.jpg
wget http://www.fosss.org/article/dabeizhou/58.jpg
wget http://www.fosss.org/article/dabeizhou/59.jpg
wget http://www.fosss.org/article/dabeizhou/60.jpg
wget http://www.fosss.org/article/dabeizhou/61.jpg
wget http://www.fosss.org/article/dabeizhou/62.jpg
wget http://www.fosss.org/article/dabeizhou/63.jpg
wget http://www.fosss.org/article/dabeizhou/64.jpg
wget http://www.fosss.org/article/dabeizhou/65.jpg
wget http://www.fosss.org/article/dabeizhou/66.jpg
wget http://www.fosss.org/article/dabeizhou/67.jpg
wget http://www.fosss.org/article/dabeizhou/68.jpg
wget http://www.fosss.org/article/dabeizhou/69.jpg
wget http://www.fosss.org/article/dabeizhou/70.jpg
wget http://www.fosss.org/article/dabeizhou/71.jpg
wget http://www.fosss.org/article/dabeizhou/72.jpg
wget http://www.fosss.org/article/dabeizhou/73.jpg
wget http://www.fosss.org/article/dabeizhou/74.jpg
wget http://www.fosss.org/article/dabeizhou/75.jpg
wget http://www.fosss.org/article/dabeizhou/76.jpg
wget http://www.fosss.org/article/dabeizhou/77.jpg
wget http://www.fosss.org/article/dabeizhou/78.jpg
wget http://www.fosss.org/article/dabeizhou/79.jpg
wget http://www.fosss.org/article/dabeizhou/80.jpg
wget http://www.fosss.org/article/dabeizhou/81.jpg
wget http://www.fosss.org/article/dabeizhou/82.jpg
wget http://www.fosss.org/article/dabeizhou/83.jpg
wget http://www.fosss.org/article/dabeizhou/84.jpg
wget http://www.fosss.org/article/dabeizhou/85.jpg
wget http://www.fosss.org/article/dabeizhou/86.jpg
wget http://www.fosss.org/article/dabeizhou/87.jpg
wget http://www.fosss.org/article/dabeizhou/88.jpg

